### ISSUE TITLE
Tasks to be done before v2 announcement from Alpha to Beta

### ISSUE THREAD

**Issue by yuhattor** [AI-Native-Development/patterns#19]
```[tasklist]
### Tasks
- [ ] Rebrand from AI-Native Development Guide to GitHub Copilot Patterns and Practices
- [ ] Encourage attention and contribution/discussion regarding patterns of low maturity
- [ ] Move old brand documents to Archived
```
